### ISSUE TITLE
Wireframing and Prototyping

### ISSUE THREAD

**Issue by danielleaop** [SchoolOfCode/final-project-innovation-collective#5]
```[tasklist]
### Tasks
- [x] Define the problem statement
- [x] User Research - Look through examples of existing products
- [ ] Define main features of landing page, chat page and profile page
- [x] User Research - Some kind of questionnaire or survey to get some data back
- [ ] User Journey - Create personas and write out journey maps
- [ ] Wireframing - draw out initial layout sketches
- [ ] Wireframing - draw out medium fidelity diagrams
- [ ] Prototype - make interactive prototypes on figma of our designs
```
