### ISSUE TITLE
MVP 1: Styling / Making components

### ISSUE THREAD

**Issue by danielleaop** [SchoolOfCode/final-project-innovation-collective#8]
```[tasklist]
### Tasks
- [x] git pull and go through install, build and run process
- [ ] create a seperate component for a profile page
- [ ] create a seperate component for a chat page
- [ ] style sign-up page
- [ ] styles profile page component
- [ ] style chat page component
```
